language: node_js
node_js:
  - node
before_install:
  - npm install -g csvtojson
  - cd csvdata/
  - sh -e processCsv.sh
  - cd $TRAVIS_BUILD_DIR
script:
  - npm run build
env:
  - PROJECT_URL=intheirownwords
after_success:
  - cd $TRAVIS_BUILD_DIR/scripts
  - sh -e makeHtaccess.sh $PROJECT_URL
  - node siteMap.js
  - cp robots.txt sitemap.xml .htaccess $TRAVIS_BUILD_DIR/dist
  - cd $TRAVIS_BUILD_DIR/dist
  - cp index.html 404.html
deploy:
  provider: pages
  verbose: true
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  keep-history: false
  target-branch: gh-pages
  on:
    branch: new_platform
