language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
before_install:
  - "npm install -g csvtojson"
  - cd csvdata/
  - sh -e processCsv.sh
script:
  - npm install
  - npm run build
after_success:
  - cd dist
  - cp index.html 404.html
deploy:
  provider: pages
  verbose: true
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  keep-history: false
  target-branch: gh-pages
  on:
    branch: vue-js
