language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm install
  - npm run build
deploy:
  provider: pages
  verbose: true
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  keep-history: false
  target-branch: gh-pages
  on:
    branch: vue-js
